version: '3.9'

services:
  nginx:
    build: ./docker/nginx
    depends_on:
      - phpfpm
    ports:
      - 8081:80
    networks:
      - web
    volumes:
      - ./data/nginx/logs:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/html/app/
    env_file:
      - .env

  phpfpm:
    build: ./docker/phpfpm
    depends_on:
      - database
    volumes:
      - ./app:/var/www/html/app/
    networks:
      - web
    env_file:
      - .env

  database:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - web
    env_file:
      - .env

networks:
  web:
